# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlayerWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from static import media

class Ui_Player(object):
    def setupUi(self, Player):
        Player.setObjectName("Player")
        Player.resize(652, 663)
        self.gridLayout_3 = QtWidgets.QGridLayout(Player)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treePlaylist = QtWidgets.QTreeView(Player)
        self.treePlaylist.setObjectName("treePlaylist")
        self.gridLayout_2.addWidget(self.treePlaylist, 1, 1, 1, 1)
        self.treePlaylists = QtWidgets.QTreeView(Player)
        self.treePlaylists.setMinimumSize(QtCore.QSize(100, 0))
        self.treePlaylists.setMaximumSize(QtCore.QSize(250, 16777215))
        self.treePlaylists.setObjectName("treePlaylists")
        self.gridLayout_2.addWidget(self.treePlaylists, 1, 0, 1, 1)
        self.belowPanel = QtWidgets.QGroupBox(Player)
        self.belowPanel.setMaximumSize(QtCore.QSize(16777215, 175))
        self.belowPanel.setObjectName("belowPanel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.belowPanel)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image = QtWidgets.QLabel(self.belowPanel)
        self.image.setMinimumSize(QtCore.QSize(100, 100))
        self.image.setMaximumSize(QtCore.QSize(100, 100))
        self.image.setText("")
        self.image.setObjectName("image")
        self.horizontalLayout.addWidget(self.image)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lName = QtWidgets.QLabel(self.belowPanel)
        self.lName.setMinimumSize(QtCore.QSize(0, 40))
        self.lName.setText("")
        self.lName.setObjectName("lName")
        self.verticalLayout_4.addWidget(self.lName)
        self.positionPanel = QtWidgets.QGroupBox(self.belowPanel)
        

        self.positionPanel.setTitle("")
        self.positionPanel.setObjectName("positionPanel")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.positionPanel)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lPosition = QtWidgets.QLabel(self.positionPanel)
        self.lPosition.setMinimumSize(QtCore.QSize(40, 0))
        self.lPosition.setObjectName("lPosition")
        self.horizontalLayout_5.addWidget(self.lPosition)
        self.slPosition = QtWidgets.QSlider(self.positionPanel)
        self.slPosition.setOrientation(QtCore.Qt.Horizontal)
        self.slPosition.setObjectName("slPosition")
        self.horizontalLayout_5.addWidget(self.slPosition)
        self.lDuratio = QtWidgets.QLabel(self.positionPanel)
        self.lDuratio.setMinimumSize(QtCore.QSize(40, 0))
        self.lDuratio.setObjectName("lDuratio")
        self.horizontalLayout_5.addWidget(self.lDuratio)
        self.verticalLayout_4.addWidget(self.positionPanel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(37, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.bBack = QtWidgets.QPushButton(self.belowPanel)
        self.bBack.setObjectName("bBack")
        self.horizontalLayout_2.addWidget(self.bBack)
        self.bPlay = QtWidgets.QPushButton(self.belowPanel)
        self.bPlay.setObjectName("bPlay")
        self.horizontalLayout_2.addWidget(self.bPlay)
        self.bStop = QtWidgets.QPushButton(self.belowPanel)
        self.bStop.setObjectName("bStop")
        self.horizontalLayout_2.addWidget(self.bStop)
        self.bNext = QtWidgets.QPushButton(self.belowPanel)
        self.bNext.setObjectName("bNext")
        self.horizontalLayout_2.addWidget(self.bNext)
        spacerItem1 = QtWidgets.QSpacerItem(37, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.sliderVolume = QtWidgets.QSlider(self.belowPanel)
        self.sliderVolume.setMaximumSize(QtCore.QSize(16777215, 100))
        self.sliderVolume.setOrientation(QtCore.Qt.Vertical)
        self.sliderVolume.setObjectName("sliderVolume")
        self.horizontalLayout.addWidget(self.sliderVolume)
        self.gridLayout_2.addWidget(self.belowPanel, 2, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(Player)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.buttonCircleAll = QtWidgets.QPushButton(Player)
        self.buttonCircleAll.setMinimumSize(QtCore.QSize(40, 0))
        self.buttonCircleAll.setMaximumSize(QtCore.QSize(40, 16777215))
        self.buttonCircleAll.setObjectName("buttonCircleAll")
        self.horizontalLayout_8.addWidget(self.buttonCircleAll)
        self.buttonRandom = QtWidgets.QPushButton(Player)
        self.buttonRandom.setMinimumSize(QtCore.QSize(40, 0))
        self.buttonRandom.setMaximumSize(QtCore.QSize(40, 16777215))
        self.buttonRandom.setObjectName("buttonRandom")
        self.horizontalLayout_8.addWidget(self.buttonRandom)
        self.buttonLoopOne = QtWidgets.QPushButton(Player)
        self.buttonLoopOne.setMinimumSize(QtCore.QSize(40, 0))
        self.buttonLoopOne.setMaximumSize(QtCore.QSize(40, 16777215))
        self.buttonLoopOne.setObjectName("buttonLoopOne")
        self.horizontalLayout_8.addWidget(self.buttonLoopOne)
        self.sorting = QtWidgets.QComboBox(Player)
        self.sorting.setObjectName("sorting")
        self.horizontalLayout_8.addWidget(self.sorting)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_8)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.savePlaylists = QtWidgets.QPushButton(Player)
        self.savePlaylists.setObjectName("savePlaylists")
        self.horizontalLayout_4.addWidget(self.savePlaylists)
        self.loadPlaylists = QtWidgets.QPushButton(Player)
        self.loadPlaylists.setObjectName("loadPlaylists")
        self.horizontalLayout_4.addWidget(self.loadPlaylists)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Player)
        QtCore.QMetaObject.connectSlotsByName(Player)

    def retranslateUi(self, Player):
        _translate = QtCore.QCoreApplication.translate
        Player.setWindowTitle(_translate("Player", "Form"))
        self.belowPanel.setTitle(_translate("Player", "~Listen for your soul...~"))
        self.lPosition.setText(_translate("Player", "00:00"))
        self.lDuratio.setText(_translate("Player", "00:00"))
        self.bBack.setText(_translate("Player", "Back"))
        self.bPlay.setText(_translate("Player", "Play"))
        self.bStop.setText(_translate("Player", "Stop"))
        self.bNext.setText(_translate("Player", "Next"))
        self.label.setText(_translate("Player", "Current Playlist"))
        self.buttonCircleAll.setText(_translate("Player", "C"))
        self.buttonRandom.setText(_translate("Player", "R"))
        self.buttonLoopOne.setText(_translate("Player", "L"))
        self.savePlaylists.setText(_translate("Player", "Save Playlists"))
        self.loadPlaylists.setText(_translate("Player", "LoadPlaylists"))
