# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RecordWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecordWidget(object):
    def setupUi(self, RecordWidget):
        RecordWidget.setObjectName("RecordWidget")
        RecordWidget.resize(563, 570)
        self.gridLayout_3 = QtWidgets.QGridLayout(RecordWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.pushButton_25 = QtWidgets.QPushButton(RecordWidget)
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_7.addWidget(self.pushButton_25)
        self.pushButton = QtWidgets.QPushButton(RecordWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_11 = QtWidgets.QLabel(RecordWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_16.addWidget(self.label_11)
        self.horizontalSlider_3 = QtWidgets.QSlider(RecordWidget)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalLayout_16.addWidget(self.horizontalSlider_3)
        self.label_12 = QtWidgets.QLabel(RecordWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_16.addWidget(self.label_12)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem1)
        self.pushButton_20 = QtWidgets.QPushButton(RecordWidget)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_17.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(RecordWidget)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_17.addWidget(self.pushButton_21)
        self.pushButton_2 = QtWidgets.QPushButton(RecordWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_17.addWidget(self.pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_15.addLayout(self.verticalLayout_6)
        self.verticalSlider = QtWidgets.QSlider(RecordWidget)
        self.verticalSlider.setMaximumSize(QtCore.QSize(100, 100))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalLayout_15.addWidget(self.verticalSlider)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 1, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.gridLayout.addLayout(self.horizontalLayout_18, 0, 0, 1, 1)
        self.scrollArea_3 = QtWidgets.QScrollArea(RecordWidget)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 350, 219))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollArea_3, 2, 1, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.label_9 = QtWidgets.QLabel(RecordWidget)
        self.label_9.setMinimumSize(QtCore.QSize(200, 0))
        self.label_9.setStyleSheet("qproperty-alignment:AlignCenter;\n"
"")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_20.addWidget(self.label_9)
        self.pushButton_22 = QtWidgets.QPushButton(RecordWidget)
        self.pushButton_22.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButton_22.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_20.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(RecordWidget)
        self.pushButton_23.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButton_23.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_20.addWidget(self.pushButton_23)
        self.pushButton_24 = QtWidgets.QPushButton(RecordWidget)
        self.pushButton_24.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButton_24.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_20.addWidget(self.pushButton_24)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        self.gridLayout.addLayout(self.horizontalLayout_19, 1, 1, 1, 1)
        self.treeView_3 = QtWidgets.QTreeView(RecordWidget)
        self.treeView_3.setMinimumSize(QtCore.QSize(100, 0))
        self.treeView_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.treeView_3.setObjectName("treeView_3")
        self.gridLayout.addWidget(self.treeView_3, 2, 0, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.comboBox_2 = QtWidgets.QComboBox(RecordWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_22.addWidget(self.comboBox_2)
        self.comboBox = QtWidgets.QComboBox(RecordWidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_22.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.horizontalLayout_22, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)

        self.retranslateUi(RecordWidget)
        QtCore.QMetaObject.connectSlotsByName(RecordWidget)

    def retranslateUi(self, RecordWidget):
        _translate = QtCore.QCoreApplication.translate
        RecordWidget.setWindowTitle(_translate("RecordWidget", "Form"))
        self.pushButton_25.setText(_translate("RecordWidget", "Stop record"))
        self.pushButton.setText(_translate("RecordWidget", "Record"))
        self.label_11.setText(_translate("RecordWidget", "00:00"))
        self.label_12.setText(_translate("RecordWidget", "00:00"))
        self.pushButton_20.setText(_translate("RecordWidget", "Stop"))
        self.pushButton_21.setText(_translate("RecordWidget", "PlayAll"))
        self.pushButton_2.setText(_translate("RecordWidget", "PlayDedicated"))
        self.label_9.setText(_translate("RecordWidget", "Dedicated record"))
        self.pushButton_22.setText(_translate("RecordWidget", "C"))
        self.pushButton_23.setText(_translate("RecordWidget", "R"))
        self.pushButton_24.setText(_translate("RecordWidget", "S"))
